### ISSUE TITLE
Add support for images in article

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#1]
Currently the generator.py file take a txt file and add the text as the article to website, implement a way to add images along with it

below is the current look of txt file

![image](https://github.com/user-attachments/assets/93dca4c7-6552-46f5-a340-deb171ed635c)

**Comment by GautamBytes** [comment]
Hey , can you please assign this issue to me?

**Comment by Aksgo** [comment]
Kindly follow the contribution guidelines

**Comment by Aksgo** [comment]
What is the progress ?

**Comment by GautamBytes** [comment]
Hey @Aksgo, i contributed to 2 issues earlier and genuinely wanted to solve this issue as well but my exams are going on now, so i can't manage extra time to do it, You can assign it to someone else. Sorry!

**Comment by Aksgo** [comment]
No issues @GautamBytes . Thanks for contribution !
