### ISSUE TITLE
add a separate function to re-update existing article

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#14]
1. add a choice for user to add anew article or update existing article in generator.py
2. for modification , the user should not input any file, it should for existing txt file (in same folder as generator.py) which have same name as html files in /public/ArticleList

**Comment by RudraJy** [comment]
Hey @Aksgo I'd like to work on this issue.

**Comment by Aksgo** [comment]
kindly follow the contribution guidelines and respect the deadline

**Comment by RudraJy** [comment]
Added a PR. Kindly verify.
