### ISSUE TITLE
show the list of articles on the left hand side (a sidebar) in each article page

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#19]
1.create a side bar which will access each article topic present in public/ArticleList adn display their topics
2.add this to article template
3. the article currently opened should come in bold

**Comment by vsnikhilvs** [comment]
Hey @Aksgo , please assign this to me

**Comment by Aksgo** [comment]
Kindly follow the contribution guidelines

**Comment by vsnikhilvs** [comment]
@Aksgo So you want the left side bar instead of the current /article page, right?
And the left bar should display all the topic titles and clicking on the title displays the article and bolden the title selected.
Am I right?

**Comment by Aksgo** [comment]
No, you shouldn't remove any element. For each article page ,currently we are are having only a container that displays the article at center. Now, We also want a sidebar (just like geeksforgeeks) for reference

**Comment by vsnikhilvs** [comment]
I mean,
There will be a side bar with all the topics. Not the current design right?
By default, the first topic will be selected.

**Comment by vsnikhilvs** [comment]
Hey @Aksgo Please give me permission to push and create a PR

**Comment by Aksgo** [comment]
@vsnikhilvs, submit a video along with the PR so that we can clearly understand what you have done

**Comment by vsnikhilvs** [comment]
> @vsnikhilvs, submit a video along with the PR so that we can clearly understand what you have done

I am unable to create a PR, the access is denied. Please give me permission to do so.

**Comment by Aksgo** [comment]
Kindly read contribution.md, you need to create a fork of this repo and then raise a Pull Request. Thanks

**Comment by Aksgo** [comment]
what is the progress ?

**Comment by GautamBytes** [comment]
Hey ,Aksgo can you please assign this issue to me if it is still opened and not merged?

**Comment by Aksgo** [comment]
If the task are not completed within 7 days then they are reassigned @GautamBytes

**Comment by vsnikhilvs** [comment]
Hey @Aksgo Apologies for the late reply. I was hospitalized. 
Regarding the issue, I have completed a minimal UI for the listing. Since we do not have a design or anything, please review it. I will post the images here. For some reason, my PC is having some issue with screen recording, its coming as black screen.

**Comment by vsnikhilvs** [comment]
![image](https://github.com/user-attachments/assets/49307da6-9e73-4ecc-82be-7d4cc45d347a)
![image](https://github.com/user-attachments/assets/34b45a61-862c-4b0a-89e8-8f21b684d22d)
The first image is the UI that I have created.
The second is showcasing a hover gradient to let the user know which item they have hovered on.
Binary is the one which is hovered

**Comment by Aksgo** [comment]
Nice work @vsnikhilvs . But please sync with the latest files first and then apply your changes.

**Comment by Aksgo** [comment]
> Hey @Aksgo Apologies for the late reply. I was hospitalized. Regarding the issue, I have completed a minimal UI for the listing. Since we do not have a design or anything, please review it. I will post the images here. For some reason, my PC is having some issue with screen recording, its coming as black screen.

No issues, thanks for your contribution !

**Comment by Aksgo** [comment]
Also Please do not forget to add comments to your code

**Comment by GautamBytes** [comment]
Hey @Aksgo , so since this issue got solved can u please assign me #62 , i have completed the issue #61 ?

**Comment by vsnikhilvs** [comment]
@Aksgo Commented the code. Created a PR. Please check and review. Thanks !

**Comment by Ritesh381** [comment]
@Aksgo I have tried to make something and created a PR kindly review
