### ISSUE TITLE
Feature: Adding Searching and Sorting Algorithms with Time complexity

### ISSUE THREAD

**Issue by codewithishu** [Aksgo/unialgo#27]
Adding Searching and Sorting Algorithms with Time complexity.

**Comment by snehautekar05** [comment]
Heyyy,@codewithishu  can you assign this issue to me?

**Comment by Aksgo** [comment]
@codewithishu kindly submit the articles in the txt file

**Comment by codewithishu** [comment]
@Aksgo I have to add it in Articlelist folder in html format?

**Comment by Aksgo** [comment]
No, since you are contributing an article please follow article contribution guidelines (in contribution.md). Just submit article following that format, rest we will handle

**Comment by codewithishu** [comment]
okay I have to submit the screenshot of my txt file in that format on my pull request

**Comment by Aksgo** [comment]
submit the file

**Comment by codewithishu** [comment]
[How Searching and Sorting Algorithm.txt](https://github.com/user-attachments/files/17274182/How.Searching.and.Sorting.Algorithm.txt)

**Comment by codewithishu** [comment]
@Aksgo is it done?

**Comment by Aksgo** [comment]
Yes, please raise a PR.

**Comment by codewithishu** [comment]
@Aksgo how can i raise pr without changing the file in project

**Comment by codewithishu** [comment]
@Aksgo Done !
