### ISSUE TITLE
hacktoberfest special - solve this question

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#32]
submit just a simple code which found the square root of number using binary search in java and cpp

**Comment by eeshsaxena** [comment]
#include <bits/stdc++.h>
using namespace std;
    
    double squareRoot(double x) {
        if (x < 0) 
        {
            cout<<"Sqaure Root no possible"<<endl;
        }
    
        double left = 0, right = x;
        double epsilon = 1e-6;
    
        while (right - left > epsilon) {
            double mid = left + (right - left) / 2;
            if (mid * mid < x) {
                left = mid;
            } else {
                right = mid;
            }
        }
        return (left + right) / 2; 
    }
    
    int main() {
        double number = 25;
        cout << "Square root of " << number << " is: " << squareRoot(number) << endl;
        return 0;
    }

**Comment by Aksgo** [comment]
kindly submit a PR of cpp file if you want a hacktoberfest-accepted label
