### ISSUE TITLE
Add a comments section at bottom of article

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#36]
1. In the article template add a comment section (only classes and id's , content should not be there as it would be handled by the generator)
2. Add sample content in public/ArticleList/huffman-coding.html
3. Upload its screenshot

**Comment by dexterousdhruv** [comment]
@Aksgo Can you please assign it to me ? I'd like to work on it.

**Comment by Aksgo** [comment]
Kindly follow the contribution guidelines.
