### ISSUE TITLE
Add a contribution tab in header

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#44]
1.You need to add a contribution tab (responsive)
2. Put a default text , -  'please sign in to view your contribution'

**Comment by Arkachau05** [comment]
interested

**Comment by Aksgo** [comment]
Kindly follow the contribution guidelines.

**Comment by Ujef55** [comment]
Hey @Aksgo could you please share the demo?

**Comment by Aksgo** [comment]
@Arkachau05 what is your progress ?

**Comment by Aksgo** [comment]
@Arkachau05 , I am unassigning you this due to finishing of 7 days time period (contributing.md). Thanks !
