### ISSUE TITLE
give a new background image for home page

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#46]

**Comment by Virtual4087** [comment]
assign me please

**Comment by Amaraja6** [comment]
can you assign me to this please?

**Comment by Aksgo** [comment]
@Amaraja6 look for other issues and contribute to them. Thanks

**Comment by Aksgo** [comment]
@Amaraja6 if you apply a scroll animation to the homepage then I will assign it to you. Something like [this](https://codepen.io/jh3y/pen/MWLPMYL)

**Comment by Madeye251002** [comment]
Hey @Amaraja6 I will do the scroll animation part can u please assign it to me?

**Comment by Aksgo** [comment]
We are closing this due to some issues. Thanks!
