### ISSUE TITLE
more articles section at last of each article

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#47]
1.Insert more articles section in ArticleTemplate.html , only section (classes and id's), no content in this file (it will be auto inserted by the generator)
2.Insert sample content in ArticleList/huffman-coding.html

**Comment by Kundanikapradhan** [comment]
hi @Aksgo please assign this issue to me

**Comment by AdibaNaushad** [comment]
can i help you with anything? .i am a fresher contributor

**Comment by Aksgo** [comment]
@AdibaNaushad look for new issues if you want to contribute
