### ISSUE TITLE
Adding 'About' tab in the header section

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#5]

**Comment by newcodergit** [comment]
Please assign me this issue under hacktoberfest 2024

**Comment by Aksgo** [comment]
Kindly create the about page (not only the header) and add following:
1.site logo
2.Sample text

**Comment by Gungunmi12** [comment]
please assign it to me

**Comment by Aksgo** [comment]
if task is not completed in 7 days then it will be re assigned

**Comment by newcodergit** [comment]
I have created a pull request kindly label the issue as hacktoberfest 2024

**Comment by Aksgo** [comment]
> I have created a pull request kindly label the issue as hacktoberfest 2024
You have not created a separate about page
