### ISSUE TITLE
Feature: Adding Graph Algorithm for competitive programming

### ISSUE THREAD

**Issue by codewithishu** [Aksgo/unialgo#50]
Adding Graph Algorithm for competitive programming

**Comment by codewithishu** [comment]
@Aksgo please assign this to me and add Hacktoberfest label

**Comment by Aksgo** [comment]
Kindly follow the article contribution guidelines

**Comment by Aksgo** [comment]
Please don't write random stuffs, explain a particular concept for a successful MR

**Comment by codewithishu** [comment]
sure
