### ISSUE TITLE
remove faq and comment from article container

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#53]
1.remove faq section and comment section from article container and add them below the article container
2.improvise their UI, also left align them

**Comment by georgioupanayiotis** [comment]
@Aksgo can you assign me this ?

**Comment by Arkachau05** [comment]
interested

**Comment by Aksgo** [comment]
kindly follow the contribution guidelines

**Comment by Aksgo** [comment]
@Arkachau05 look for other issues and contribute to them

**Comment by georgioupanayiotis** [comment]
@Arkachau05 i have created the PR here https://github.com/Aksgo/unialgo/pull/57 thanks for assigning me! 🙂
