### ISSUE TITLE
Fix the Menu drop down bug on the article section of the website

### ISSUE THREAD

**Issue by Pujan-khunt** [Aksgo/unialgo#55]
- Currently, when opening the website's article section, the menu drop shouldn't appear as it should only be for mobile users.

Fix:
1. remove that menu drop-down from the header and add the normal header.
2. add that menu drop-down for mobile users.

![image](https://github.com/user-attachments/assets/79247ca4-d657-41d8-8ca7-8d31b067b2fc)

**Comment by Pujan-khunt** [comment]
@Aksgo Can i be assigned to this issue as I have already worked on a similar issue before on this project?

**Comment by Aksgo** [comment]
Yes, just put three bars when menu is not opened instead of writing 'menu' there
