### ISSUE TITLE
Add a scroll animation to home page

### ISSUE THREAD

**Issue by Aksgo** [Aksgo/unialgo#62]
1. Add a good scroll animation to home page

**Comment by GautamBytes** [comment]
Hey @Aksgo , can you please assign this issue to me?

**Comment by Aksgo** [comment]
Kindly complete the task assigned first @GautamBytes

**Comment by Daksh-134** [comment]
Hi @Aksgo can you please assign this to me

**Comment by hemangtk** [comment]
hey! @Aksgo could you please explain the issue in detail so i can provide my take on this and then if you are okay later i can start working on the issue
