### ISSUE TITLE
Add a footer page 

### ISSUE THREAD

**Issue by yeshwanth-ds** [Aksgo/unialgo#66]
I would like to add the footer page wor this project 
I would like you to assigne me this task under apporiate level tags.

**Comment by Aksgo** [comment]
@yeshwanth-ds Please wait till 14th October. Thanks

**Comment by Aksgo** [comment]
@yeshwanth-ds you do it but include separate styles and js for your work

**Comment by Aksgo** [comment]
@yeshwanth-ds what is the progress ?

**Comment by saurav2208** [comment]
Is this issue still open? If yes then I would like to be assigned @Aksgo

**Comment by Aksgo** [comment]
Kindly follow the contribution guidelines
