### ISSUE TITLE
On how Dijkstra's Algorithm (Shortest Path) works ?

### ISSUE THREAD

**Issue by yeshwanth-ds** [Aksgo/unialgo#9]
I would create a new block like to create a new block in the acticlr page, nameing it "How Dijkstra's Algorithm (Shortest Path) works ?".
This alogrithu comes under greedy algorithms. Then one click on this block will render a page where i will explain about Dijkstra's Algorithm (Shortest Path). The key points i will mention in this page are How Dijkstra's Algorithm Works, Steps of Dijkstra's Algorithm, Example, Time Complexity , Limitations i will make sure to mention all about this in this new page.

I will aslo keep the design in sync with the other articles to have a clean user friendly experince

I will add the block here:
![Screenshot 2024-10-02 123153](https://github.com/user-attachments/assets/1f400c48-d092-46c9-830f-ad4b3a30a480)

I would like you to assign me this task under hacktoberfest tag.

**Comment by Aksgo** [comment]
Kindly follow the guidelines of txt file you will add in PR.

**Comment by Aksgo** [comment]
thanks for contribution
