### ISSUE TITLE
Overall styling improvement and code formatting

### ISSUE THREAD

**Issue by TonyStark-19** [Aksgo/unialgo#91]
Your project is great.
I want to work on this project as a whole. 
I will add CSS-related improvements and format the code to increase its readability and make it easy for future contributors to understand and work on the code.

**Comment by Aksgo** [comment]
Hi @TonyStark-19, Thanks for reaching out! To contribute, please start by opening relevant issues with appropriate tags and a description of the changes you want to make. Once an issue is assigned to you, you can create a PR with required changes.

**Comment by TonyStark-19** [comment]
I will work on the footer layout, About us section and the article page.
Will add slight animation to the contribution page.
Will improve the animation of all articles list 
Although it is still in development , a subtle animation can still make it look good

**Comment by Aksgo** [comment]
Ok, kindly submit a screenshot of your changes in PR
